### ISSUE TITLE
Panel de admin

### ISSUE THREAD

**Issue by JechsonRodriguez** [PaulGuillen/EcommerceRestaurant#2]
Hola puedes subir el panel de administracion completo, el que subio no tiene para iniciar sesion como en las capturas que subio, gracias 
![Captura de pantalla 2022-07-17 184158](https://user-images.githubusercontent.com/105475784/179429800-256de7b3-4cc4-4873-b7c6-ce6c02ec622b.png)

**Comment by PaulGuillen** [comment]
![image](https://user-images.githubusercontent.com/43099030/179434017-7641da4e-dbd4-42d9-9063-cd9a03d7d9aa.png)
Gracias por avisarme, si lo acabo de subir.

Puedes usar este usuario de prueba 
Correo : pedro123456@gmail.com
Contraseña : pedro123456

Nota : En la seccion Pedidos quite los links de bootstrap porque me generaban un error al cargar los datos, pero puedes importarlo de la misma pagina creo que es por algun tema de version.

No olvides si tienes alguna duda enviarme un mensaje.

Saludos

**Comment by JechsonRodriguez** [comment]
Hola , acabo de verlo otra vez y ahora no inicia sesion ,adjunto captura del problema . 
![Captura de pantalla 2022-07-17 210500](https://user-images.githubusercontent.com/105475784/179435597-31d87b61-4a8d-4211-94f6-a4638d925faf.png)

**Comment by PaulGuillen** [comment]
Prueba creandote un usuario en la opcion registro

**Comment by JechsonRodriguez** [comment]
tampoco funciona , a ti te funciona?
![Captura de pantalla 2022-07-17 212031](https://user-images.githubusercontent.com/105475784/179436523-47981241-eaf2-4ace-97c1-4ec353b333f8.png)

**Comment by PaulGuillen** [comment]
![image](https://user-images.githubusercontent.com/43099030/179436742-6b958874-ce4b-490a-93b8-1e0b5dda55fb.png)

![image](https://user-images.githubusercontent.com/43099030/179436866-e173e200-2ec9-43a1-a4bc-90d56a067546.png)


Si que raro debe ser algo , bueno el unico problema es la vulneracion del password

**Comment by JechsonRodriguez** [comment]
puedes conectarte a discord o teams para ver ese problema?

**Comment by PaulGuillen** [comment]
Mandame tu ID de discord

**Comment by JechsonRodriguez** [comment]
phoenix_luffy#2459
